"""add table2

Revision ID: 06d5c9ed5083
Revises: 3d482f51603b
Create Date: 2025-03-02 07:17:49.391528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '06d5c9ed5083'
down_revision: Union[str, None] = '3d482f51603b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current bind (connection)
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind) # type: ignore
    # Check if the table already exists
    if 'Table2' not in inspector.get_table_names():
        op.create_table('Table2',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Table2')
    # ### end Alembic commands ###
