"""add tag

Revision ID: 3d482f51603b
Revises: c86374d5de4a
Create Date: 2025-03-02 07:10:35.674135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '3d482f51603b'
down_revision: Union[str, None] = 'c86374d5de4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current bind (connection)
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind) # type: ignore
    if 'tag' not in [col['name'] for col in inspector.get_columns('Table1')]:
        op.add_column('Table1', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Table1', 'tag')
    # ### end Alembic commands ###
