"""initial version

Revision ID: c86374d5de4a
Revises: 
Create Date: 2025-03-02 07:01:05.764089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'c86374d5de4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current bind (connection)
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind) # type: ignore
    # Check if the table already exists
    if 'Table1' not in inspector.get_table_names():
        op.create_table('Table1',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Table1')
    # ### end Alembic commands ###
