"""add table2

Revision ID: 02a239078787
Revises: 74a231c89304
Create Date: 2025-03-02 08:03:55.184336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '02a239078787'
down_revision: Union[str, None] = '74a231c89304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind) # type: ignore
    # Check if the table already exists
    if 'Table2' not in inspector.get_table_names():
        op.create_table('Table2',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Table2')
    # ### end Alembic commands ###
