"""add description to table1

Revision ID: 40721bc192ec
Revises: 02a239078787
Create Date: 2025-03-02 08:07:56.105230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '40721bc192ec'
down_revision: Union[str, None] = '02a239078787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind) # type: ignore
    if 'description' not in [col['name'] for col in inspector.get_columns('Table1')]:
        op.add_column('Table1', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Table1', 'description')
    # ### end Alembic commands ###
